export const SUPABASE_FOCUSPOND_BASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_FOCUSPOND_BASE_URL;

export const SUPABASE_FOCUSPOND_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_FOCUSPOND_ANON_KEY;

export const SUPABASE_FOCUSPOND_SERVICE_ROLE_KEY =
  process.env.SUPABASE_FOCUSPOND_SERVICE_ROLE_KEY;
