// src/lib/db/indexedDB.ts

import Dexie, { Table } from "dexie";
import type { MoodLevel, EnergyLevel } from "@/features/mood/constants/moods";

// Why liveQuery() exists

// liveQuery() is for cases like:

// A dashboard that should update automatically when DB changes

// Multiple tabs reacting to the same DB

// Analytics views that must reflect data instantly

// Example use case:

// “When a mood is saved, update the dashboard graph without refetching.”

// If you want next, I can:

// Help you batch sync efficiently

// Design analytics queries (patterns, streaks, trends)

export interface MoodEntry {
  id?: number; // Dexie auto-generates it
  level: MoodLevel;
  label: string;
  note?: string; // Optional: 'user_skipped', 'onboarding_flow'
  energyLevel: EnergyLevel;
  createdAt?: Date;
  synced?: boolean; // Has this been sent to Supabase? (false = pending)
}
export interface Task {
  id?: number; // Auto-generated by Dexie
  title: string;
  description?: string;

  // Energy matching (for mood-based suggestions)
  energyRequired: EnergyLevel; // 'high' | 'medium' | 'low'

  // Priority & time
  priority: "high" | "medium" | "low";
  estimatedMinutes: number; // How long user thinks it'll take (15, 30, 60, etc.)

  // Pomodoro tracking
  pomodoroCount?: number; // How many pomodoros user allocated (auto-calculated from estimatedMinutes)
  pomodorosCompleted?: number; // How many pomodoros done so far (0 initially)

  // Frog task
  isFrogTask: boolean; // Is this the "eat the frog" task?

  // Status
  completed: boolean; // false initially, true when done
  createdAt: Date; // When task was created
  completedAt?: Date; // When task was marked complete (undefined until done)

  // Sync with backend
  synced?: boolean; // false = needs to sync to Supabase, true = already synced
}

export interface PomodoroSession {
  id?: number;
  taskId?: number; // Optional: can be linked to a task or standalone
  startTime: Date;
  endTime?: Date; // undefined if session is still running
  duration: number; // In minutes (25, 15, 50, etc.)
  completed: boolean; // Did they complete the full session?
  mood?: MoodLevel; // Optional: their mood during this session
  synced?: boolean;
}

export class FocusPondDB extends Dexie {
  // Define tables (like tables in SQL)
  moods!: Table<MoodEntry, number>; // Table name: 'moods', Primary key type: number
  tasks!: Table<Task, number>;
  pomodoros!: Table<PomodoroSession, number>;

  constructor() {
    super("FocusPondDB"); // Database name (stored as 'FocusPondDB' in browser)

    /**
     * Define database schema (structure)
     *
     * The string syntax:
     * '++id' = Auto-incrementing primary key
     * 'level' = Create index on this field (for faster queries)
     * 'timestamp' = Create index on this field
     * 'synced' = Create index on this field
     *
     * Indexes allow fast queries like:
     * - db.moods.where('level').equals('high')
     * - db.moods.where('synced').equals(false)
     */
    this.version(1).stores({
      moods: "++id, level, createdAt",
      tasks: "++id, priority, energyRequired, createdAt",
      pomodoros: "++id, taskId, startTime",
    });
  }
}

// ============================================
// 3. CREATE DATABASE INSTANCE
// ============================================

/**
 * Export a single instance of the database
 * This is what components will use
 */
export const db = new FocusPondDB();

// ============================================
// 4. HELPER FUNCTIONS FOR MOODS
// ============================================

/**
 * These are convenience functions to make working with moods easier
 */
export const moodDB = {
  /**
   * Add a new mood entry
   *
   * Usage:
   * await moodDB.add({ level: 'high', timestamp: new Date() })
   *
   * What happens:
   * 1. Dexie auto-generates an 'id' (1, 2, 3, etc.)
   * 2. Saves to IndexedDB on user's device
   * 3. Returns the generated id
   */

  async add(mood: Omit<MoodEntry, "id">) {
    // 'Omit<MoodEntry, 'id'>' means "all MoodEntry fields EXCEPT id"
    // Because Dexie auto-generates the id
    return await db.moods.add({
      ...mood,
      createdAt: new Date(),
      synced: false,
    });
  },

  async getLatest(): Promise<MoodEntry | undefined> {
    return await db.moods.orderBy("createdAt").reverse().first();
  },

  async getToday(): Promise<MoodEntry | undefined> {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    return await db.moods
      .where("createdAt")
      .between(today, tomorrow, true, false)
      .first();
  },

  async getTodayMoods(): Promise<MoodEntry[]> {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    return await db.moods
      .where("createdAt")
      .between(today, tomorrow, true, false)
      .toArray();
  },

  /**
   * Get all moods that haven't been synced to Supabase yet
   *
   * This is used when internet comes back online
   */
  async getUnsynced(): Promise<MoodEntry[]> {
    return await db.moods.filter((mood) => mood.synced === false).toArray();
  },

  /**
   * Mark a mood as synced after successfully sending to Supabase
   */
  async markAsSynced(id: number): Promise<number> {
    return await db.moods.update(id, { synced: true });
  },

  /**
   * Get all moods (for analytics)
   */
  async getAll(): Promise<MoodEntry[]> {
    return await db.moods.toArray();
  },
};

// ============================================
// 5. HELPER FUNCTIONS FOR TASKS
// ============================================

export const taskDB = {
  /**
   * Add a new task
   *
   * Usage:
   * await taskDB.add({
   *   title: 'Write proposal',
   *   energyRequired: 'high',
   *   priority: 'high',
   *   estimatedMinutes: 60,
   *   isFrogTask: true,
   *   completed: false,
   *   createdAt: new Date()
   * });
   */

  async add(task: Omit<Task, "id">): Promise<number> {
    const pomodoroCount = Math.ceil(task.estimatedMinutes / 25);
    return await db.tasks.add({
      ...task,
      pomodoroCount,
      pomodorosCompleted: 0,
      synced: false,
    });
  },

  /**
   * Get all incomplete tasks
   */
  async getIncomplete(): Promise<Task[]> {
    return await db.tasks.filter((task) => task.completed === false).toArray();
  },

  /**
   * Get all frog tasks (incomplete)
   */
  async getFrogTasks(): Promise<Task[]> {
    return await db.tasks
      .filter((task) => task.isFrogTask === true && task.completed === false)
      .toArray();
  },

  /**
   * Get tasks by energy level
   */
  async getByEnergy(energy: EnergyLevel): Promise<Task[]> {
    return await db.tasks
      .where("energyRequired")
      .equals(energy)
      .filter((task) => task.completed === false)
      .toArray();
  },

  /**
   * Mark task as complete
   */
  async complete(id: number): Promise<number> {
    return await db.tasks.update(id, {
      completed: true,
      completedAt: new Date(),
      synced: false, // Need to sync this change
    });
  },

  /**
   * Toggle frog task status
   */
  async toggleFrogTask(id: number, isFrog: boolean): Promise<number> {
    return await db.tasks.update(id, {
      isFrogTask: isFrog,
      synced: false,
    });
  },

  /**
   * Update task (general purpose)
   */
  async update(id: number, updates: Partial<Task>): Promise<number> {
    return await db.tasks.update(id, {
      ...updates,
      synced: false, // Mark as needing sync
    });
  },

  /**
   * Get unsynced tasks
   */

  async getUnsynced(): Promise<Task[]> {
    return await db.tasks.filter((task) => task.synced === false).toArray();
  },

  /**
   * Mark as synced
   */
  async markAsSynced(id: number): Promise<number> {
    return await db.tasks.update(id, { synced: true });
  },

  /**
   * Get all tasks
   */
  async getAll(): Promise<Task[]> {
    return await db.tasks.toArray();
  },

  /**
   * Delete a task
   */
  async delete(id: number): Promise<void> {
    await db.tasks.delete(id);
  },
};

// ============================================
// 6. HELPER FUNCTIONS FOR POMODOROS
// ============================================

export const pomodoroDB = {
  /**
   * Start a new pomodoro session
   */
  async start(
    taskId: number | undefined,
    duration: number = 25
  ): Promise<number> {
    return await db.pomodoros.add({
      taskId,
      startTime: new Date(),
      duration,
      completed: false,
      synced: false,
    });
  },

  /**
   * Complete a pomodoro session
   */
  async complete(id: number): Promise<number> {
    const session = await db.pomodoros.get(id);

    if (session?.taskId) {
      const task = await db.tasks.get(session.taskId);
      if (task) {
        await db.tasks.update(session.taskId, {
          pomodorosCompleted: (task.pomodorosCompleted || 0) + 1,
          synced: false,
        });
      }
    }

    return await db.pomodoros.update(id, {
      endTime: new Date(),
      completed: true,
      synced: false,
    });
  },

  /**
   * Get today's pomodoro sessions
   */
  async getToday(): Promise<PomodoroSession[]> {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    return await db.pomodoros.where("startTime").aboveOrEqual(today).toArray();
  },

  /**
   * Get unsynced pomodoros
   */

  async getUnsynced(): Promise<PomodoroSession[]> {
    return await db.pomodoros
      .filter((pomodoro) => pomodoro.synced === false)
      .toArray();
  },

  /**
   * Mark as synced
   */
  async markAsSynced(id: number): Promise<number> {
    return await db.pomodoros.update(id, { synced: true });
  },
};
